# Generated by Django 4.2.4 on 2023-08-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(default='cover_def.png', upload_to='books'),
        ),
    ]
