# Generated by Django 4.2.4 on 2023-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pic',
            field=models.ImageField(default='grey_skull.png', upload_to='sellers'),
        ),
    ]
