# Generated by Django 4.2.4 on 2023-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custs', '0005_alter_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(default='no notes'),
        ),
    ]
